Repository commandprompt/pgmanage, pull requests merged in 2025-08, with the labels that each got.

#709 708 configuration snapshot difference error
  pgmanage/app/static/pgmanage_frontend/src/components/ConfigTab.vue
Labels: bug

#718 External prettytable lib instead of custom internal
  pgmanage/app/include/Spartacus/Database.py
  pgmanage/app/include/Spartacus/prettytable.py
  pgmanage/pgmanage-server.py
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: refactoring

#711 Python 3.11 upgrade
  BUILD.md
  deploy/linux/tarbuild/Dockerfile
  deploy/macosx/README.md
  deploy/macosx/deploy.sh
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#697 Refactoring/sql query templates
  pgmanage/app/include/OmniDatabase/MariaDB.py
  pgmanage/app/include/OmniDatabase/MySQL.py
  pgmanage/app/include/OmniDatabase/Oracle.py
  pgmanage/app/include/OmniDatabase/PostgreSQL.py
  pgmanage/app/include/OmniDatabase/SQLite.py
  pgmanage/app/include/OmniDatabase/sql_templates/__init__.py
  pgmanage/app/include/OmniDatabase/sql_templates/mariadb.py
  pgmanage/app/include/OmniDatabase/sql_templates/mysql.py
  pgmanage/app/include/OmniDatabase/sql_templates/oracle.py
  pgmanage/app/include/OmniDatabase/sql_templates/postgres.py
  pgmanage/app/include/OmniDatabase/sql_templates/sqlite.py
  pgmanage/app/views/tree_mariadb.py
  pgmanage/app/views/tree_mysql.py
  pgmanage/app/views/tree_oracle.py
  pgmanage/app/views/tree_postgresql.py
  pgmanage/app/views/tree_sqlite.py
Labels: refactoring

#692 Refactoring/omnidatabase variables naming
  pgmanage/app/client_manager/client_manager.py
  pgmanage/app/include/OmniDatabase/MariaDB.py
  pgmanage/app/include/OmniDatabase/MySQL.py
  pgmanage/app/include/OmniDatabase/Oracle.py
  pgmanage/app/include/OmniDatabase/PostgreSQL.py
  pgmanage/app/include/OmniDatabase/SQLite.py
  pgmanage/app/include/Session.py
  pgmanage/app/tests/test_postgresql12.py
  pgmanage/app/utils/conf.py
  pgmanage/app/views/backup.py
  pgmanage/app/views/connections.py
  pgmanage/app/views/monitoring_dashboard.py
  pgmanage/app/views/polling.py
  pgmanage/app/views/restore.py
  pgmanage/app/views/tree_mariadb.py
  pgmanage/app/views/tree_mysql.py
  pgmanage/app/views/tree_oracle.py
  pgmanage/app/views/tree_postgresql.py
  pgmanage/app/views/tree_sqlite.py
  pgmanage/app/views/workspace.py
Labels: refactoring

#723 Spartacus database variables renaming
  pgmanage/app/client_manager/client_manager.py
  pgmanage/app/include/OmniDatabase/__init__.py
  pgmanage/app/include/Session.py
  pgmanage/app/include/Spartacus/Database.py
  pgmanage/app/tests/test_postgresql12.py
  pgmanage/app/tests/utils_testing.py
  pgmanage/app/views/connections.py
  pgmanage/app/views/polling.py
  pgmanage/app/views/restore.py
  pgmanage/app/views/workspace.py
  pgmanage/pgmanage-server.py
Labels: refactoring

#728 keep query notice formatting, add colorized log-level labels
  pgmanage/app/static/pgmanage_frontend/src/assets/scss/common/typography.scss
  pgmanage/app/static/pgmanage_frontend/src/assets/scss/common/ui-elements.scss
  pgmanage/app/static/pgmanage_frontend/src/components/QueryResultTabs.vue
Labels: enhancement

#729 Ssl deprecation fix
  pgmanage/pgmanage-server.py
Labels: enhancement
